name: C++ CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest manually
      run: sudo apt-get install -y libgtest-dev libeigen3-dev cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls -a && cd lib && sudo cp *.a /usr/lib
    - name: configure
      run: mkdir build && cd build && cmake -DTESTMAF=ON ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: cd build/lib && ./runMafLibTests
