name: C++ CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest manually
      run: sudo apt-get install -y libeigen3-dev
    - name: configure
      run: mkdir build && cd build && cmake -DTESTMAF=ON ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: cd build/lib && ./runMafLibTests
